"use strict";

module.exports = {
	config: {
		backgroundColor: "#29284E",
		bell: "",
		borderColor: "#4C487B",
		colors: {
			black: "#000000",
			red: "#FF628C",
			green: "#A5FF90",
			yellow: "#FAD000",
			blue: "#6A76FB",
			magenta: "#FB94FF",
			cyan: "#9EFFFF",
			white: "#C7C7C7",
			lightBlack: "#686868",
			lightRed: "#FF628C",
			lightGreen: "#A5FF90",
			lightYellow: "#FAD000",
			lightBlue: "#6A76FB",
			lightMagenta: "#B362FF",
			lightCyan: "#9EFFFF",
			lightWhite: "#FFFFFF",
			limeGreen: "#32CD32",
			lightCoral: "#F08080",
		},
		copyOnSelect: true,
		cursorAccentColor: "#000",
		cursorBlink: true,
		cursorColor: "#FAD000",
		cursorShape: "BLOCK",
		defaultSSHApp: true,
		disableAutoUpdates: false,
		disableLigatures: false,
		fontFamily: "DankMono-Regular",
		fontSize: 16,
		fontWeight: "normal",
		fontWeightBold: "bold",
		foregroundColor: "#E0E0E7",
		letterSpacing: 0,
		lineHeight: 1.45,
		macOptionSelectionMode: "vertical",
		padding: "1.25rem",
		quickEdit: false,
		selectionColor: "#7448AF",
		shellArgs: ["--login"],
		updateChannel: "stable",
		webGLRenderer: false,
	},
	localPlugins: [],
	plugins: [],
	keymaps: {},
};
